version: "3.7"
services:
  go-db:
    image: mysql:8.0
    command: --lower_case_table_names=1
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=langgo
      - MYSQL_ROOT_PASSWORD=root-pass
      - MYSQL_USER=gogo
      - MYSQL_PASSWORD=gogo
      - TZ=UTC
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql:/var/lib/mysql